import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

import {
  GITHUB_APP_ID_VARIABLE,
  GITHUB_APP_PRIVATE_KEY_VARIABLE,
  isValidAppId,
  isValidInstallationId,
  loadGitHubAppConfig,
  looksLikePemPrivateKey,
} from './config.ts';

/** Obviously fake — random bytes, never generated by or registered with GitHub. Safe to commit. */
// pragma: fixture — synthetic, invalid key material; see the module comment above.
const FAKE_PRIVATE_KEY =
  '-----BEGIN RSA PRIVATE KEY-----\nTk9UQUJFQUxLRVkuTk9UQUJFQUxLRVkuTk9UQUJFQUxLRVk=\n-----END RSA PRIVATE KEY-----'; // pragma: fixture

const VALID_ENV = {
  [GITHUB_APP_ID_VARIABLE]: '123456',
  [GITHUB_APP_PRIVATE_KEY_VARIABLE]: FAKE_PRIVATE_KEY,
};

describe('isValidAppId', () => {
  it('accepts a positive integer string', () => {
    assert.equal(isValidAppId('123456'), true);
    assert.equal(isValidAppId('1'), true);
  });

  it('rejects zero, negative, non-numeric, and float-shaped values', () => {
    for (const value of ['0', '-5', 'abc', '1.5', '1e3', '0x10', '', ' ', '123 ']) {
      assert.equal(isValidAppId(value), false, `${JSON.stringify(value)} should be rejected`);
    }
  });
});

describe('isValidInstallationId', () => {
  it('accepts a positive integer', () => {
    assert.equal(isValidInstallationId(1), true);
    assert.equal(isValidInstallationId(4242), true);
  });

  it('rejects zero, negative, non-integer, and non-number values', () => {
    for (const value of [0, -1, 1.5, '4242', null, undefined, {}, [], NaN, Infinity]) {
      assert.equal(isValidInstallationId(value), false, `${JSON.stringify(value)} should be rejected`);
    }
  });
});

describe('looksLikePemPrivateKey', () => {
  it('accepts a well-formed PEM block', () => {
    assert.equal(looksLikePemPrivateKey(FAKE_PRIVATE_KEY), true);
  });

  it('accepts a non-RSA-labelled PEM block', () => {
    assert.equal(
      looksLikePemPrivateKey('-----BEGIN PRIVATE KEY-----\nZmFrZQ==\n-----END PRIVATE KEY-----'), // pragma: fixture
      true,
    );
  });

  it('rejects a value missing the PEM header or footer', () => {
    assert.equal(looksLikePemPrivateKey('just some random text'), false);
    assert.equal(looksLikePemPrivateKey('-----BEGIN RSA PRIVATE KEY-----\nZmFrZQ=='), false); // pragma: fixture
  });

  it('rejects an empty string', () => {
    assert.equal(looksLikePemPrivateKey(''), false);
  });
});

describe('loadGitHubAppConfig', () => {
  it('resolves when both variables are valid', () => {
    const result = loadGitHubAppConfig(VALID_ENV);
    assert.ok(result.configured);
    assert.equal(result.config.appId, 123456);
    assert.equal(result.config.privateKey, FAKE_PRIVATE_KEY);
  });

  it('is not configured when GITHUB_APP_ID is missing', () => {
    const { [GITHUB_APP_ID_VARIABLE]: _drop, ...rest } = VALID_ENV;
    const result = loadGitHubAppConfig(rest);
    assert.equal(result.configured, false);
    assert.match(result.reason, new RegExp(GITHUB_APP_ID_VARIABLE));
  });

  it('is not configured when GITHUB_APP_PRIVATE_KEY is missing', () => {
    const { [GITHUB_APP_PRIVATE_KEY_VARIABLE]: _drop, ...rest } = VALID_ENV;
    const result = loadGitHubAppConfig(rest);
    assert.equal(result.configured, false);
    assert.match(result.reason, new RegExp(GITHUB_APP_PRIVATE_KEY_VARIABLE));
  });

  it('is not configured when both variables are missing, and names both', () => {
    const result = loadGitHubAppConfig({});
    assert.equal(result.configured, false);
    assert.match(result.reason, new RegExp(GITHUB_APP_ID_VARIABLE));
    assert.match(result.reason, new RegExp(GITHUB_APP_PRIVATE_KEY_VARIABLE));
  });

  it('treats a blank GITHUB_APP_ID as missing, not as invalid', () => {
    const result = loadGitHubAppConfig({ ...VALID_ENV, [GITHUB_APP_ID_VARIABLE]: '   ' });
    assert.equal(result.configured, false);
    assert.match(result.reason, /not set/);
  });

  it('rejects a malformed GITHUB_APP_ID', () => {
    const result = loadGitHubAppConfig({ ...VALID_ENV, [GITHUB_APP_ID_VARIABLE]: '0' });
    assert.equal(result.configured, false);
    assert.match(result.reason, /invalid/);
  });

  it('rejects a non-numeric GITHUB_APP_ID', () => {
    const result = loadGitHubAppConfig({ ...VALID_ENV, [GITHUB_APP_ID_VARIABLE]: 'not-a-number' });
    assert.equal(result.configured, false);
    assert.match(result.reason, /invalid/);
  });

  it('rejects a malformed GITHUB_APP_PRIVATE_KEY', () => {
    const result = loadGitHubAppConfig({ ...VALID_ENV, [GITHUB_APP_PRIVATE_KEY_VARIABLE]: 'not a pem key' });
    assert.equal(result.configured, false);
    assert.match(result.reason, /invalid/);
  });

  describe('secret-safe error messages', () => {
    it('never includes the private key value in the reason for a missing key', () => {
      const { [GITHUB_APP_PRIVATE_KEY_VARIABLE]: _drop, ...rest } = VALID_ENV;
      const result = loadGitHubAppConfig(rest);
      assert.equal(result.configured, false);
      assert.ok(!result.reason.includes('BEGIN'), 'the reason should never quote key material');
    });

    it('never includes the malformed key value in the reason for an invalid key', () => {
      const malformedKey = 'TOTALLY-NOT-A-KEY-BUT-STILL-SECRET-SHAPED-VALUE';
      const result = loadGitHubAppConfig({ ...VALID_ENV, [GITHUB_APP_PRIVATE_KEY_VARIABLE]: malformedKey });
      assert.equal(result.configured, false);
      assert.ok(!result.reason.includes(malformedKey), 'the reason leaked the invalid key value');
    });

    it('never includes the app id value in the reason for an invalid app id', () => {
      const result = loadGitHubAppConfig({ ...VALID_ENV, [GITHUB_APP_ID_VARIABLE]: 'super-secret-looking-id' });
      assert.equal(result.configured, false);
      assert.ok(!result.reason.includes('super-secret-looking-id'));
    });
  });
});
