import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { ObjectId } from 'mongodb';

import { generateBranchName, validateBranchName } from './branch-name.ts';

describe('generateBranchName', () => {
  it('is deterministic for the same run and execution', () => {
    const runId = new ObjectId();
    const executionId = new ObjectId();
    assert.equal(generateBranchName(runId, executionId), generateBranchName(runId, executionId));
  });

  it('is unique per execution, even for the same run', () => {
    const runId = new ObjectId();
    const a = generateBranchName(runId, new ObjectId());
    const b = generateBranchName(runId, new ObjectId());
    assert.notEqual(a, b);
  });

  it('is prefixed with aisdlc/ and repository-relative (never absolute)', () => {
    const name = generateBranchName(new ObjectId(), new ObjectId());
    assert.match(name, /^aisdlc\/[0-9a-f]{24}\/[0-9a-f]{24}$/);
  });
});

describe('validateBranchName', () => {
  it('accepts a name generated by generateBranchName', () => {
    const name = generateBranchName(new ObjectId(), new ObjectId());
    assert.deepEqual(validateBranchName(name, 'main'), { ok: true });
  });

  it('refuses a branch name equal to the base branch', () => {
    const result = validateBranchName('main', 'main');
    assert.equal(result.ok, false);
    assert.equal(result.ok === false && result.reason, 'protected_branch');
  });

  it('refuses main and master regardless of the base branch', () => {
    for (const name of ['main', 'master', 'Main', 'MASTER']) {
      const result = validateBranchName(name, 'develop');
      assert.equal(result.ok, false, `${name} should be refused`);
      assert.equal(result.ok === false && result.reason, 'protected_branch');
    }
  });

  it('refuses an empty or whitespace-only name', () => {
    for (const name of ['', '   ', ' aisdlc/x ']) {
      const result = validateBranchName(name, 'main');
      assert.equal(result.ok, false, `${JSON.stringify(name)} should be refused`);
    }
  });

  it("refuses a '..' sequence", () => {
    const result = validateBranchName('aisdlc/../escape', 'main');
    assert.equal(result.ok, false);
    assert.equal(result.ok === false && result.reason, 'invalid_ref_name');
  });

  it('refuses a leading, trailing, or doubled slash', () => {
    for (const name of ['/aisdlc/x', 'aisdlc/x/', 'aisdlc//x']) {
      const result = validateBranchName(name, 'main');
      assert.equal(result.ok, false, `${name} should be refused`);
    }
  });

  it("refuses a name ending in '.lock'", () => {
    const result = validateBranchName('aisdlc/x.lock', 'main');
    assert.equal(result.ok, false);
  });

  it('refuses shell/control characters', () => {
    for (const name of ['aisdlc/x y', 'aisdlc/x;rm', 'aisdlc/x\0y', 'aisdlc/x~1']) {
      const result = validateBranchName(name, 'main');
      assert.equal(result.ok, false, `${JSON.stringify(name)} should be refused`);
    }
  });

  it('requires the aisdlc/ prefix', () => {
    const result = validateBranchName('feature/something', 'main');
    assert.equal(result.ok, false);
    assert.equal(result.ok === false && result.reason, 'invalid_ref_name');
  });
});
